<a href="https://colab.research.google.com/github/1kalyan/ML-from-scratch/blob/main/01%20Introduction_to_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Numpy
What will we cover?
- Creating arrays
- multi dimensional array
- Randomly generated arrays
- Element wise operations
    - Comparision Operations
    - Logical Operations
- Summarizing Operations

## Single Dimensional array


In [1]:
import numpy as np


###Creating Array


In [3]:
var = np.zeros(5);
print(type(var))

<class 'numpy.ndarray'>


<!-- np.zeros(10) -->

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

###Defining our own **array**

In [11]:
var = np.array([1, 2 , 3, 4])

In [16]:
var[2] = 5
var[-1] = 6
print(var)

[1 2 5 6]


###Range of number in numpy


In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

### Create array with evenly spaced numbers within a specific range


In [20]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##Multi Dimensional arrays


In [22]:
np.zeros((5,2)) #5 row 2 column

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
#Create a MUd unit array of size (5,2)
np.ones((5,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
#create a random array of size(3,5) with elements using random integer

np.array(np.random.randint(5, size=(3,5)))



#create a random array of size(3,5) with elements using number of your choice

updatingA = np.array([[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10],
                      [1, 5, 6, 7, 8]])
print(updatingA)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  5  6  7  8]]


In [36]:
# update the element of an array with index
updatingA[1,2] = 88
print(updatingA)

[[ 1  2  3  4  5]
 [ 6  7 88  9 10]
 [ 1  5  6  7  8]]


In [51]:
updatingA[2] = 1
updatingA[ : , 2] = [2 , 3, 5]
print(updatingA)

[[ 1  2  2  4  5]
 [ 6  7  3  9 10]
 [ 1  1  5  1  1]]


## 🍀🃏Randomly Generated arrays

- NumPY can create arrays filled with random number

- To ensure the reproducibility  you can use Seed can be use to control the randomness that is np.random.seed()

- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers
# New section
     If you remove or change the seed values, the sequence of random numbers will be changed


In [55]:
np.random.rand(3)

array([0.87452718, 0.31352841, 0.69600069])

In [71]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [81]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [77]:
np.random.seed(2)
np.random.randint(1 , 100 , 5)

array([41, 16, 73, 23, 44])

In [91]:
np.random.randn(5,2) #normally distributed

array([[-0.36794457,  2.1114884 ],
       [-1.02957349, -1.33628031],
       [-0.61056736,  0.52469426],
       [-0.34930813, -0.44073846],
       [-1.1212876 ,  1.47284473]])

In [92]:
# Define the NumPy array
arr = np.array([[-0.36794457,  2.1114884 ],
                [-1.02957349, -1.33628031],
                [-0.61056736,  0.52469426],
                [-0.34930813, -0.44073846],
                [-1.1212876 ,  1.47284473]])

# Calculate mean
mean_all = np.mean(arr)  # Mean of all elements
mean_row = np.mean(arr, axis=1)  # Mean of each row
mean_col = np.mean(arr, axis=0)  # Mean of each column

# Calculate standard deviation
std_all = np.std(arr)  # Standard deviation of all elements
std_row = np.std(arr, axis=1)  # Standard deviation of each row
std_col = np.std(arr, axis=0)  # Standard deviation of each column

# Print results
print("Mean of all elements:", mean_all)
print("Mean of each row:", mean_row)
print("Mean of each column:", mean_col)
print("Standard deviation of all elements:", std_all)
print("Standard deviation of each row:", std_row)
print("Standard deviation of each column:", std_col)

Mean of all elements: -0.11466725300000002
Mean of each row: [ 0.87177191 -1.1829269  -0.04293655 -0.39502329  0.17577856]
Mean of each column: [-0.69573623  0.46640172]
Standard deviation of all elements: 1.0816130512808162
Standard deviation of each row: [1.23971648 0.15335341 0.56763081 0.04571517 1.29706616]
Standard deviation of each column: [0.32473214 1.24861536]


In [95]:
np.random.seed(42)
np.random.randint(low = 0 , high = 100 , size = [5,2])

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### Element wise operations


In [96]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [97]:
b = (10+ (a*2))
b

array([10, 12, 14, 16, 18])

In [98]:
#Comprasion operations

# You can perform element wise comprasion and create boolean array
a >= 2

array([False, False,  True,  True,  True])

In [99]:
a > b

array([False, False, False, False, False])

In [100]:
a[4] > b[0]

False

In [105]:
#summarizing
#Numpy provides functions for summarizind array of data
a

array([0, 1, 2, 3, 4])

In [107]:
#standard deviation
a.std()

1.4142135623730951

In [108]:
#min vaule od an array
a.min()

0

In [109]:
#max value of an array
a.max()

4

In [110]:
#sum of elements of an array
a.sum()

10

In [112]:
#mean of array
a.mean()

2.0